/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniHelloService */

#ifndef _Included_JniHelloService
#define _Included_JniHelloService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniHelloService
 * Method:    ping
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniHelloService_ping
  (JNIEnv *, jobject);

/*
 * Class:     JniHelloService
 * Method:    calculateSquare
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_JniHelloService_calculateSquare
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     JniHelloService
 * Method:    exampleMethod
 * Signature: (Lch/obermuhlner/rpc/example/api/ExampleData;)Lch/obermuhlner/rpc/example/api/ExampleData;
 */
JNIEXPORT jobject JNICALL Java_JniHelloService_exampleMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     JniHelloService
 * Method:    adapterExampleMethod
 * Signature: (Lch/obermuhlner/rpc/example/api/AdapterExampleData;)Lch/obermuhlner/rpc/example/api/AdapterExampleData;
 */
JNIEXPORT jobject JNICALL Java_JniHelloService_adapterExampleMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     JniHelloService
 * Method:    exampleFailure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniHelloService_exampleFailure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
